In [117]:
SUBIR_A_KAGGLE = True

</br>
<div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #555555; padding-bottom: 15px; margin-bottom: -8px;">
    <div style="width: 50%;">
        <h2>
            <span style="color: #B30033;">▍</span>Práctica 1:
        </h2>
        <h1 style="margin-top: -10px;">
            Análisis, procesamiento y validación
        </h1>
    </div>
    <div style="width: 50%; text-align: right;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-top: 30px;">
            <div style="width: 20%;"></div>
            <div style="width: 80%; border-left: 2px solid #555555; padding-left: 20px;">
                <div style="margin-bottom: 20px;">
                    <p style="margin: 0; font-size: 1.4em; font-weight: bold;">
                        Minería de Datos, 2025-26
                    </p>
                </div>
                <div style="margin-top: 8px; text-align: right;">
                    <span style="font-size: 1em; color: #D0D0D0;">
                        José Antonio Gámez Martín
                    </span>
                    <a href="mailto:Jose.Gamez@uclm.es" style="text-decoration: none; color: #888888; font-size: 0.8em; padding-left: 15px;">
                        ✉ Jose.Gamez@uclm.es
                    </a>
                </div>
                <div style="margin-top: 8px; text-align: right;">
                    <span style="font-size: 1em; color: #D0D0D0;">
                        Pablo Torrijos Arenas
                    </span>
                    <a href="mailto:Pablo.Torrijos@uclm.es" style="text-decoration: none; color: #888888; font-size: 0.8em; padding-left: 15px;">
                        ✉ Pablo.Torrijos@uclm.es
                    </a>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="border-bottom: 2px solid #555555; padding-bottom: 25px; margin-bottom: 10px">
    <div style="display: flex; align-items: center; margin-bottom: 10px;">
        <span style="color: #B30033; font-size: 1.5em; margin-right: 10px;">▍</span>
        <h3 style="margin: 0; font-size: 1.4em; font-weight: bold">
            Estudiantes
        </h3>
    </div>
    <ul style="list-style-type: none; padding-left: 28px; margin: 0;  font-size: 1.1em">
        <li>Alberto Pérez Álvarez</li>
        <li>Diego García Díaz</li>
    </ul>

</div>

## 1. Introducción

El objetivo de esta práctica es aplicar las técnicas de un flujo de trabajo de **minería de datos** para resolver un problema de **clasificación supervisada**. Se analizará un conjunto de datos sobre el rendimiento y la actividad de estudiantes universitarios para predecir la probabilidad de abandono de sus estudios.

El desarrollo abarcará desde el **análisis exploratorio** de los datos y su **preprocesamiento**, hasta el **entrenamiento** de un modelo y su **validación** robusta. 

El rendimiento de los modelos se evaluará en una competición privada en Kaggle, que abarcará esta Práctica 1 y la Práctica 2 (selección de modelos).

<div style="border-bottom: 2px solid #555555; padding-bottom: 15px; margin-bottom: 10px">

## 2. Carga y visualización de los datos

Se proporciona un conjunto de datos sintético que simula el rendimiento académico y la interacción de estudiantes durante su primer año. Los datos contienen una variedad de tipos de variables, valores faltantes y otros artefactos que deberán ser gestionados.

Comenzamos importando las librerías necesarias y cargando los conjuntos de datos de entrenamiento (`train`) y de prueba (`test`) para poder examinarlos:

In [118]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

df_train_raw = pd.read_csv('./csv/uclm_student_train.csv')
df_train_raw

,id,nombre,nacimiento,provincia,residencia_id,trabaja,horas_trabajo,bachillerato,nota_acceso,modalidad,creditos_a1,superados_a1,nota_s1,satisfaccion,horas_moodle,posts_foro,uso_biblioteca,eventos,tutorias,comentarios,numero_fav,talla_zapato,color_fav,meses_matriculado,grupo_trabajo,abandono
0,TO-2010-GCA531,Graciano Cano Alsina,1992-05-06,Albacete,E1-P02-H04,0,NaN,Científico,6.08,Tiempo completo,60,60,8.16,4.32,~7.2 horas,2,11,1,4,relacion correcto con compañeros,71,43,Azul oscuro,6,GR10335,1
1,CU-2016-MBP239,María Belén Polo,1998-10-31,Cuenca,E2-P03-H06,0,NaN,CIENCIAS PURAS,8.12,Tiempo completo,60,60,9.09,4.05,~11.8 horas,13,2,2,0,Uso normal de la plataforma Moodle,22,38,Coral claro,6,GR13813,0
2,CR-2010-JS201,Judith Sáenz,1992-03-11,Ciudad Real,NaN,0,NaN,Ciencias Puras,10.59,Tiempo completo,60,54,7.99,3.88,~8.8 horas,6,14,2,3,NaN,69,37,Violeta oscuro,6,GR02505,0
3,TO-2016-CDB602,Casandra de Bautista,1998-11-03,Toledo,E1-P04-H18,0,NaN,Humanidades,7.85,Tiempo completo,60,48,7.27,3.81,~8.7 horas,0,0,2,3,Relacion adecuado con compañeros.,3,34,Rosa profundo,6,GR14887,0
4,AB-2011-CAA364,Carlito Alvarado Anaya,1993-12-22,Albacete,NaN,0,NaN,ECONÓMICO,10.23,Tiempo completo,60,60,8.45,4.08,~9.6 horas,16,6,2,3,ha mejorado notablemente en asignaturas troncales,19,39,Coral claro,5,GR09244,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40540,AB-2011-CB913,Cecilia Bosch,1993-04-14,Albacete,NaN,0,NaN,CIENCIAS SOCIALES,8.64,Tiempo completo,60,36,5.52,2.94,~1.1h,8,0,3,0,NaN,23,39,Rojo violeta medio,6,GR15949,1
40541,TO-2011-WRL313,Wilfredo Roda Lerma,1987-11-12,Toledo,NaN,1,NaN,Económico,10.59,Tiempo completo,60,60,9.00,4.05,~11.5 horas,8,2,3,2,NaN,76,40,Amarillo,6,GR11547,0
40542,CR-2017-JA946,Javi Acuña,1999-09-05,Ciudad Real,NaN,0,NaN,TECNOLÓGICO,10.41,Tiempo completo,60,54,NaN,3.52,~5.1 horas,3,8,4,4,Expresa dudas sobre continuar los estudios.,24,40,Gris claro,4,GR00625,1
40543,AB-2010-TRM306,Teresita Rodrigo Morera,1992-06-23,Albacete,NaN,0,NaN,Económico,10.15,Tiempo completo,60,54,7.36,3.70,~8.0 horas,10,3,4,0,NaN,39,38,Azul real,6,GR06859,0
40544,CU-2012-OTB162,Odalys Talavera Baena,1994-08-04,Cuenca,NaN,0,NaN,CCSS,7.78,Tiempo completo,60,60,8.92,4.28,"~9,7 horas",0,9,3,3,Entrega adecuada de tareas.,44,38,Negro,6,GR07618,0

In [119]:
df_test_raw = pd.read_csv('csv/uclm_student_test.csv')
df_test_raw

,id,nombre,nacimiento,provincia,residencia_id,trabaja,horas_trabajo,bachillerato,nota_acceso,modalidad,creditos_a1,superados_a1,nota_s1,satisfaccion,horas_moodle,posts_foro,uso_biblioteca,eventos,tutorias,comentarios,numero_fav,talla_zapato,color_fav,meses_matriculado,grupo_trabajo
0,AB-2019-FEM764,Fabiola Espejo Marín,2002-01-12,Ciudad Real,E1-P01-H01,0,NaN,CCSS,10.17,Tiempo completo,60,48,7.74,3.81,~11.0 horas,16,14,5,5,Expresa dudas sobre su vocacion.,43,40,Violeta sonrojado pálido,6,GR01091
1,TO-2018-ALL744,Arsenio Lucas Llanos,2000-06-13,Toledo,NaN,0,NaN,Letras,9.16,Tiempo completo,60,48,6.99,3.28,~6.8 horas,2,5,5,1,NaN,88,40,Cian,6,GR02931
2,AB-2018-ZSD099,Zaira Salvà Dominguez,2000-09-25,Albacete,NaN,0,NaN,Ciencias Puras,8.91,Tiempo completo,60,60,8.28,4.48,10.0,12,2,6,2,Busca activamente prácticas y oportunidades pr...,96,39,Gris oscuro,3,GR06795
3,CR-2019-TCS733,Tatiana Celia Solano Tejera,2001-06-05,Ciudad Real,NaN,0,NaN,Letras,9.29,Tiempo completo,60,24,3.96,1.86,~0.8 horas,10,6,3,1,NaN,62,38,Blanco lavanda,6,GR06712
4,CR-2018-VBV597,Victoriano Benavente Vilaplana,2000-06-18,Ciudad Real,NaN,0,NaN,Letras,5.00,Tiempo completo,60,0,2.85,1.26,~5.9 horas,17,2,2,0,NaN,98,44,Azul Alicia,2,GR01653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9582,AB-2019-AAM365,Albino Acero Múgica,2002-02-14,Albacete,NaN,0,NaN,Tecnológico Industrial,9.38,Tiempo completo,60,30,4.74,2.20,~4.2 horas,11,1,5,0,NaN,98,41,Marrón siena,6,GR13835
9583,AB-2019-MC507,Marina Calleja,2002-01-07,Albacete,NaN,0,NaN,CCSS,6.41,Tiempo completo,60,60,9.52,4.97,~8.4 horas,3,7,6,2,Asistencia constante a clases.,33,38,Amarillo,6,GR14729
9584,AB-2019-MNC716,Morena Noelia Castell Amor,2001-04-05,Albacete,NaN,0,NaN,Letras,9.60,Tiempo completo,60,24,5.09,2.35,7.8,2,9,2,2,Habla de cambiar de ciudad por motivos persona...,96,35,Azul anciano,6,GR11046
9585,AB-2018-ICH450,Isidora Cabrera Hoyos,2001-02-09,Albacete,NaN,1,NaN,CCSS,9.79,Tiempo completo,60,48,7.05,3.59,11.5,12,1,2,2,NaN,82,37,Blanco,6,GR10480
9586,CU-2019-CL671,Carmen Lluch-Vega,2001-08-03,Cuenca,NaN,0,NaN,Artes,6.15,Tiempo completo,60,60,8.59,4.40,~7.2 horas,4,12,0,0,NaN,52,37,Verde mar claro,6,GR03195

Las variables disponibles son:
`id`, `nombre`, `nacimiento`, `provincia`, `residencia_id`, `trabaja`, `horas_trabajo`, `bachillerato`, `nota_acceso`, `modalidad`, `creditos_a1`, `superados_a1`, `nota_s1`, `satisfaccion`, `horas_moodle`, `posts_foro`, `uso_biblioteca`, `eventos`, `tutorias`, `comentarios`, `numero_fav`, `talla_zapato`, `color_fav`, `meses_matriculado`, `grupo_trabajo`, `abandono`.

La variable objetivo es `abandono`, que es binaria:
* **1**: El estudiante abandona los estudios.
* **0**: El estudiante continúa.

Se puede observar cómo hay variables categóricas, numéricas, fechas, texto, valores faltantes... Esto requerirá de un análisis exploratorio y un preprocesamiento.

<div style="border-bottom: 2px solid #555555; padding-bottom: 15px; margin-bottom: 10px">

## 3. Flujo de Trabajo y Requisitos

El desarrollo de la práctica deberá seguir las siguientes etapas:


### 3.1. Análisis Exploratorio de Datos (EDA)

Se debe realizar un análisis inicial para comprender la naturaleza de los datos. Este análisis debe incluir:
* Distribución de la variable objetivo (`abandono`).
* Análisis de valores faltantes.
* Distribución de las variables numéricas y categóricas, valores únicos, outliers...
* Identificación de valores atípicos.
* Relaciones entre las variables y la variable objetivo.

Las conclusiones de este análisis deben servir para justificar las decisiones tomadas en la siguiente etapa.


### 3.2. Preprocesamiento de Datos

Esta etapa es fundamental para preparar los datos antes de la modelización. Las tareas incluyen la imputación de valores faltantes, la codificación de variables categóricas, la ingeniería de características (ej. creación de nuevas variables a partir de las existentes), el escalado de datos o incluso eliminar variables que nos aporten información

Este proceso debe de ir totalmente ligado al EDA. Las conclusiones que hayamos sacado en el estudio son las que nos deben guiar en este paso. Del mismo modo, al preprocesar los datos y entrenar los modelos podemos sacar nuevas conclusiones que nos permitan entender mejor los datos (como habéis visto en **CRISP-DM**):

<img src="https://upload.wikimedia.org/wikipedia/commons/b/b9/CRISP-DM_Process_Diagram.png" alt="Diagrama de Proceso CRISP-DM" width="550"/>

**Requisito obligatorio**: Todo el proceso de transformación de datos **debe** encapsularse en `Pipelines` de `scikit-learn`. En la práctica, además de mantener una mayor claridad y estructura en el código, esto nos ayudará a evitar fugas de datos.


### 3.3. Modelización y Validación

Se debe entrenar y evaluar correctamente **al menos un algoritmo** (ej. Árboles de Decisión, Naive Bayes, etc.). En esta práctica no es importante usar el mejor modelo posible (eso vendrá en la Práctica 2), sino analizar, preparar y evaluar bien los datos.

**Requisito obligatorio**: La evaluación y comparación de los modelos **debe** realizarse mediante una estrategia de **validación cruzada**. Además, es imporante tener en cuenta distintas **métricas** para evaluar nuestro modelo.


### 3.4. Predicción y Evaluación

El modelo final se puede utilizar para generar predicciones sobre el conjunto `uclm_student_test.csv`. Esto es recomendable, pero no es obligatorio en esta práctica (lo será en la Práctica 2).

El fichero de predicciones deberá seguir el formato especificado en `sample_submission.csv`:

In [120]:
df_kaggle = pd.read_csv('csv/sample_submission.csv')
df_kaggle

                  id  abandono
0     AB-2019-FEM764         1
1     TO-2018-ALL744         1
2     AB-2018-ZSD099         0
3     CR-2019-TCS733         0
4     CR-2018-VBV597         0
...              ...       ...
9582  AB-2019-AAM365         0
9583   AB-2019-MC507         1
9584  AB-2019-MNC716         0
9585  AB-2018-ICH450         0
9586   CU-2019-CL671         0

[9587 rows x 2 columns]

<div style="border-bottom: 2px solid #555555; margin-bottom: 10px">

## 4. Competición en Kaggle

La evaluación final se realizará mediante una competición privada en Kaggle. El objetivo es maximizar la métrica **F1-Score**, una medida robusta que tiene en cuenta tanto la precisión como la exhaustividad, especialmente útil en casos con clases desbalanceadas.

* **Enlace a la competición**: https://www.kaggle.com/t/16fef7f5d88c4dd399f8bad259c55947

Los equipos con mejor rendimiento en el *private leaderboard* recibirán una bonificación en la nota final:
* **1er puesto**: +0.75 puntos.
* **2º puesto**: +0.5 puntos.
* **3er puesto**: +0.25 puntos.

**Nota**: Las bonificaciones están sujetas a la revisión del código y la metodología. Se podrá requerir una justificación del enfoque para verificar la originalidad y la comprensión del trabajo.

## Importaciones adicionales

In [121]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import unicodedata
import category_encoders as ce
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.impute import KNNImputer
from sklearn.discriminant_analysis import StandardScaler
from sklearn.preprocessing import RobustScaler
from sklearn.impute import SimpleImputer

from sklearn.base import BaseEstimator, TransformerMixin # Para el imputer personalizado
from sklearn.model_selection import KFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import cross_validate
import warnings

import tempfile
import shutil
from joblib import parallel_backend
import gc
import platform

### Función auxiliar para detectar el SO

In [122]:
def get_os_type():
    system = platform.system()
    
    if system == "Linux":
        return "linux"
    elif system == "Darwin":
        # Darwin es Macos, por algún motivo
        return "macos"
    else:
        return "other"

## Análisis de los datos

### Tipos de clases

In [123]:
# Variables discretas (valores enteros contables, como categorías codificadas o conteos)
categorical_cols = [
    "trabaja",
    "creditos_a1",
    "superados_a1",
    "uso_biblioteca",
    "eventos",
    "tutorias",
    "numero_fav",
    "meses_matriculado",
    "provincia",
    "bachillerato",
    "modalidad",
    "comentarios",
    "residencia_id", # Da mejor DT, algo peor NB
    "talla_zapato", # Aumenta la puntuación, (y como categórica más) por lo que sea
]

# Variables continuas (valores numéricos con posibles decimales)
numerical_cols = [
    "nota_acceso",
    "nota_s1",     
]

mnar_cols = [
    "horas_moodle",  # Necesita pasarse de string a float
    "horas_trabajo",    # Muchos NaN, si son todos NaN habría que quitarla
    "satisfaccion",
]

# Variables de texto libre (respuestas abiertas, tipo string)
string_cols = [
    "color_fav",    # Como categorica da menos
    "id",
    "nombre",
    "grupo_trabajo", # Como categorica da menos
]

# Variables de fechas
date_cols = [
    "nacimiento"
]

useless = [
    "posts_foro", # baja la puntuación
]

### Tratamiento variables especiales

In [ ]:
df_train = df_train_raw.copy()
df_train["horas_moodle"] = df_train["horas_moodle"].str.extract(r'([\d.]+)').astype(float)

df_test = df_test_raw.copy()
df_test["horas_moodle"] = df_test["horas_moodle"].str.extract(r'([\d.]+)').astype(float)
'''
# TRATAMIENTO DE FECHAS a priori a naive bayes le viene peor
for column in date_cols: # En caso de añadir más fechas por algún motivo
    df_train[column] = pd.to_datetime(df_train[column], errors='coerce')
    
    # Cómo son cíclicas usamos el seno para que se tenga en cuenta que diciembre está al lado de enero
    df_train['year'] =  df_train[column].dt.year
    df_train['month_sin']= np.sin(2 * np.pi * df_train[column].dt.month / 12)
    df_train['month_cos']= np.cos(2 * np.pi * df_train[column].dt.month / 12)
    df_train['day']  = df_train[column].dt.day

    df_dummies = pd.get_dummies(df_train['day'], prefix='day')

    #df_train.drop(column, axis=1)
    df_train = pd.concat([df_train,df_dummies], axis=1)
    dates = ['year','month_sin','month_cos']
    numerical_cols.extend(dates)

    day_dummies = [f'day_{i}' for i in range(1, 32)]
    numerical_cols.extend(day_dummies)

#print(df_train)
'''


class DateFeatureTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass

    def fit(self, X, y=None):
        self.output_features_ = ['year', 'month_sin', 'month_cos'] + [f'day_{i}' for i in range(1, 32)]
        return self

    def transform(self, X):     
        date_series = pd.to_datetime(X.iloc[:, 0], errors='coerce')

        X_transformed = pd.DataFrame()
        
        # Creamos la categorías
        X_transformed['year'] = date_series.dt.year
        month_values = date_series.dt.month
        X_transformed['month_sin'] = np.sin(2 * np.pi * month_values / 12) # De esta manera el modelo tiene en cuenta que el mes 12 es seguido del 1
        X_transformed['month_cos'] = np.cos(2 * np.pi * month_values / 12)

        # One-hot para los dias del mes
        day_values = date_series.dt.day
        X_transformed['day'] = day_values
        day_dummies = pd.get_dummies(day_values, prefix='day', dummy_na=False)
        
        # Comprobamos que todos los dias estan presentes, y si no los añadimos
        for day in range(1, 32): 
            col_name = f'day_{day}'
            if col_name not in day_dummies.columns:
                day_dummies[col_name] = 0
        
        # Reordenamos según el día
        day_dummies = day_dummies[[f'day_{day}' for day in range(1, 32)]]
        
        X_transformed = pd.concat([X_transformed, day_dummies], axis=1)

        return X_transformed

### Limpieza de variables categóricas

In [ ]:
FILL_VALUE = 'Desconocido'

class TextCleanerImputer(BaseEstimator, TransformerMixin):
    def __init__(self, fill_value=FILL_VALUE):
        self.fill_value = fill_value

    def fit(self, X, y=None):
        '''Es necesario un método fit para compatibilidad con scikit pipeline, aunque esté vacío'''
        return self

    def _remove_accents(self, text):
        if pd.isna(text):
            return text
        return ''.join(
            c for c in unicodedata.normalize('NFKD', str(text))
            if not unicodedata.combining(c)
        )

    def transform(self, X):
        X_transformed = X.copy()
        for col in X_transformed.columns:
            X_transformed[col] = (
                X_transformed[col]
                .fillna(self.fill_value)
                .astype(str)
                .str.lower()
                .apply(self._remove_accents)
                .str.strip()
                .str.replace(r'[\"\.,]', '', regex=True)
                .str.replace(r'\s+', ' ', regex=True)
            )
        return X_transformed

"\nEjemplo de uso en un pipeline de sklearn:\n\ncategorical_pipeline = Pipeline(steps=[\n    ('text_cleaner', TextCleanerImputer(fill_value='Desconocido')),\n    ('encoder', OneHotEncoder(handle_unknown='ignore')) # o el que queramos\n])\n\npreprocessor = ColumnTransformer(transformers=[\n    ('cat', categorical_pipeline, categorical_cols)\n])\n\nmodel = Pipeline(steps=[\n    ('preprocessor', preprocessor),\n    ('classifier', RandomForestClassifier())\n])\n\n"

### Limpieza de variables numéricas

In [ ]:
# TODO: Probar más imputadores.

imputer_numerical = KNNImputer(n_neighbors=7)

imputer_mnar_DT = SimpleImputer(strategy='median', add_indicator=True)
imputer_mnar_NB = SimpleImputer(strategy='mean', add_indicator=True) # Con constant da lo mimso tb

## Pipelines

### Inicialización

In [ ]:
# Pipeline para Categóricas (Limpieza y luego Encoding) (Podriamos usarla en un futuro para strings, o no, ya veremos)

text_pipeline = Pipeline([
    ('limpiador_texto', TextCleanerImputer(fill_value=FILL_VALUE)),
])

# Pipelines para Numéricas (Imputación KNN)
numerical_pipeline_robustScaler = Pipeline([
    ('imputador_knn', imputer_numerical),
    ('scaler', RobustScaler(quantile_range=(25.0, 75.0))) # Peor rendimiento
])

numerical_pipeline = Pipeline([
    ('imputador_knn', imputer_numerical),
    ('scaler', StandardScaler())
])

numerical_pipeline_mnar_DT = Pipeline([
    ('imputador_mnar', imputer_mnar_DT),
    ('scaler', StandardScaler())
])

numerical_pipeline_mnar_NB = Pipeline([
    ('imputador_mnar', imputer_mnar_NB),
    ('scaler', StandardScaler())
])

date_pipeline = Pipeline([
    ('date_creator', DateFeatureTransformer()), 
    ('imputador_knn', imputer_numerical),
    ('scaler', StandardScaler())
])

### Preprocesador (Aplicar imputación y limpieza)

In [ ]:
preprocessor_DT = ColumnTransformer(
    transformers=[
        # Aplicamos la limpieza de texto a las categóricas
        ('cat_proc', text_pipeline, categorical_cols), 
        # Aplicamos la imputación a numéricas
        ('num_proc', numerical_pipeline, numerical_cols),
        # Aplicamos la imputación a las numéricas que queremos mantener la falta de información
        ('num_mnar_proc', numerical_pipeline_mnar_DT, mnar_cols),
        # Aplicamos preprocesamiento a las fechas
        #('date_proc', date_pipeline, date_cols)  Baja la puntuación en kaggle
    ],

    remainder='drop', # drop para que solo deje las columnas especificadas (numerical y categorical _cols) y quite el resto
                             # passthrough para que mantenga todas

    verbose_feature_names_out=False # Para que no prefije nombres de transformadores a las features
)

preprocessor_NB = ColumnTransformer(
    transformers=[
        # Aplicamos la limpieza de texto a las categóricas
        ('cat_proc', text_pipeline, categorical_cols), 
        # Aplicamos la imputación a numéricas
        ('num_proc', numerical_pipeline, numerical_cols),
        # Aplicamos la imputación a las numéricas que queremos mantener la falta de información
        ('num_mnar_proc', numerical_pipeline_mnar_NB, mnar_cols),
        # A Naive Bayes no le sienta bien las fechas
    ],

    remainder='drop', # drop para que solo deje las columnas especificadas (numerical y categorical _cols) y quite el resto
                             # passthrough para que mantenga todas

    verbose_feature_names_out=False # Para que no prefije nombres de transformadores a las features
)

## Tratamiento de categóricas para los modelos

### Target encoder

In [129]:
target_encoder = ce.TargetEncoder(smoothing=10.0)

## Entrenamiento de los modelos

In [130]:
SEED = 42

### Separación y dropeo de variables

In [131]:
columns_to_drop = string_cols #+ date_cols

# Separamos el dataset de las variables a quitar
X_train = df_train.drop(columns=['abandono']).drop(columns=columns_to_drop)
y_train = df_train['abandono']

X_test = df_test.drop(columns=columns_to_drop)

# Verificar columnas faltantes entre train y test
missing_cols = set(X_train.columns) - set(X_test.columns)
if missing_cols:
    print(f"Columnas ausentes en test: {missing_cols}")

### Árbol de decisión

In [132]:
arbol_decision = DecisionTreeClassifier(random_state=SEED)

pipeline_DT = Pipeline([
    # Imputación, Limpieza de Texto (No usa 'y')
    ('preprocessor', preprocessor_DT), 
    
    # Target Encoding (SÍ usa 'y' de entrenamiento del fold)
    ('encoder', target_encoder), 
    
    # Modelo de Clasificación/Regresión
    ('modelo', arbol_decision) 
])

#pipeline_DT.fit(X_train, y_train)

### Naive Bayes

In [133]:
naive_bayes = GaussianNB()

pipeline_NB = Pipeline([
    # Imputación, Limpieza de Texto (No usa 'y')
    ('preprocessor', preprocessor_NB), 
    
    # Target Encoding (SÍ usa 'y' de entrenamiento del fold)
    ('encoder', target_encoder), 
    
    # Modelo de Clasificación/Regresión
    ('modelo', naive_bayes) 
])

#pipeline_NB.fit(X_train,y_train)

##  Cross validation

### Downcasting de variables para que ocupen menos en memoria
Reducir todas las variables posibles de 64 bits a 32 o 16 bits. Necesario para usar el pipeline con n_jobs=-1 con 16 GB de RAM.
Penaliza mucho en kaggle pero para la cross-validation en train no altera prácticamente el resultado.

In [134]:
threads = -1
def do_downcasting():
    threads = -1

    cols_to_reduce = X_train.select_dtypes(include=np.number).columns

    for col in cols_to_reduce:
        # Downcast de floats (float64 a float32)
        if X_train[col].dtype == np.float64:
            X_train[col] = X_train[col].astype(np.float32)
        # Downcast de integers (int64 a int32 o int16)
        elif X_train[col].dtype == np.int64:
            # Comprobamos el rango
            X_train[col] = pd.to_numeric(X_train[col], downcast='integer')

    # Columnas a optimizar (categorical/string)
    categorical_cols = X_train.select_dtypes(include=['object', 'category']).columns

    for col in categorical_cols:
        # Convertir objetos string a dtype para más eficiencia
        X_train[col] = X_train[col].astype('category')

    for col in categorical_cols:
        current_categories = list(X_train[col].cat.categories)
        
        if FILL_VALUE not in current_categories:
            new_categories = current_categories + [FILL_VALUE]
            
            # Poner las catagorías en el DataFrame
            X_train[col] = X_train[col].cat.set_categories(new_categories)

    return threads

if (not SUBIR_A_KAGGLE):
    threads = do_downcasting()

### Funciones para ejecutar la validación cruzada

In [ ]:
# Archivo temporal para usar como caché
if get_os_type() == "linux":
    SSD_TEMP_DIR = "/mnt/ntfs/kosos/alber/Linux/PYTHON/temp"
else:
    SSD_TEMP_DIR = tempfile.mkdtemp()

cv = KFold(n_splits=5, shuffle=True, random_state=SEED)

scoring_metrics = ['accuracy', 'f1']

def run_cross_validation(model_pipeline):
    return cross_validate(
        estimator=model_pipeline, 
        X=X_train, 
        y=y_train, 
        cv=cv, 
        scoring=scoring_metrics,  
        n_jobs=threads # -1 = Todos los cores
    )

def get_stats(cv_results):
    mean_accuracy = cv_results['test_accuracy'].mean()
    std_accuracy = cv_results['test_accuracy'].std()
    mean_f1 = cv_results['test_f1'].mean()
    std_f1 = cv_results['test_f1'].std()

    return (mean_accuracy, std_accuracy, mean_f1, std_f1)

def print_results(mean_accuracy, std_accuracy, mean_f1, std_f1):
    print(f"Cross-validation accuracy: {mean_accuracy:.4f} ± {std_accuracy:.4f}")
    print(f"Cross-validation F1-score: {mean_f1:.4f} ± {std_f1:.4f}")

def cross_validation(model_pipeline):
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", category=FutureWarning)  # Filtrar los avisos de "futuro"

            # Backend de paralelismo bloqueando los procesos paralelos (n_jobs) a usar exclusivamente un hilo (Ahorro de memoria, menos duplicación)
            with parallel_backend('loky', temp_folder=SSD_TEMP_DIR,inner_max_num_threads=1):
                cv_results = run_cross_validation(model_pipeline)

        (mean_accuracy, std_accuracy, mean_f1, std_f1) = get_stats(cv_results)

        print_results(mean_accuracy, std_accuracy, mean_f1, std_f1)

        model_pipeline.fit(X_train, y_train) # Para sacar el predict posteriormente
        
    finally:
        # Eliminar los archivos temporales de caché
        shutil.rmtree(SSD_TEMP_DIR, ignore_errors=True)

### Árbol de decisión

In [136]:
gc.collect()
#del df_train_raw
cross_validation(pipeline_DT)

Cross-validation accuracy: 0.7807 ± 0.0061
Cross-validation F1-score: 0.5787 ± 0.0086

### Naive Bayes

In [137]:
gc.collect()
cross_validation(pipeline_NB)

Cross-validation accuracy: 0.7877 ± 0.0053
Cross-validation F1-score: 0.5620 ± 0.0051

## Predicción de los modelos

### Árbol de decisión

In [138]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)  # Filtrar los avisos de "futuro"
    
    tree_predict = pipeline_DT.predict(X_test)

### Naive Bayes

In [139]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=FutureWarning)  # Filtrar los avisos de "futuro"
    
    bayes_predict = pipeline_NB.predict(X_test)

## Predicciones a CSV

In [140]:
predictions = [
    ("decision_tree",tree_predict)
    ,
    ("naive_bayes",bayes_predict)
    ]

def predictsToCsv():
    for (model_name,prediction) in predictions:
        output = pd.DataFrame({
            "id": df_test_raw["id"],
            "abandono": prediction
        })

        output.to_csv("./predictions/"+model_name+".csv",index=False)

if (SUBIR_A_KAGGLE):   
    predictsToCsv()